//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<int> Create_At { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Products Products { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
